language: ruby
jobs:
  include:
    - rvm: 2.7
      dist: focal
    - rvm: 2.6
      dist: bionic
    - rvm: 2.5
      dist: xenial
before_install:
  - export LIBTORCH_VERSION=1.7.0
  - ./test/ci/install_libtorch.sh
cache:
  bundler: true
  directories:
    - $HOME/libtorch
before_script: bundle exec rake compile -- --with-torch-dir=$HOME/libtorch/$LIBTORCH_VERSION
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
